// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */


 public class Constants {

    // k values for the arm PID
    public static final double kTurnToleranceDeg = 400;
    public static final double kTurnRateToleranceDegPerS = 3000;

    // USB Ports
    public static int JOYDRIVER_USB_PORT = 0;

    // CAN IDs
    public static int DRIVETRAIN_LEFT_FRONT = 11;
    public static int DRIVETRAIN_LEFT_BACK = 13;
    public static int DRIVETRAIN_RIGHT_FRONT = 12;
    public static int DRIVETRAIN_RIGHT_BACK = 14;
    public static int SHOULDER_MOTOR = 22;
    public static int ARM_MOTOR = 21;

    //Encoder ports
    public static int ENCODER_ARM_A = 2;
    public static int ENCODER_ARM_B = 3;
    public static int ENCODER_SHOULDER_A = 0;
    public static int ENCODER_SHOULDER_B = 1;

    //Shoulder Constants
    public static double MAX_SHOULDER_VELOCITY = 0.4;

    //Arm Constants
    public static double MAX_ARM_VELOCITY = 0.4;
    public static double ARM_SPEED = 0.3;
    public static int DIO_SWITCH_ARM_IN = 4;

    // Driving constants
    public static final double DRIVER_SLOWDOWN = .5;

};


